# netlify.toml - VERSI BENAR
[build]
  publish = ".next"  # UNTUK NEXT.JS, BUKAN "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js plugin untuk optimasi
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects untuk CMS - INI PENTING!
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Redirects untuk Next.js - INI PENTING!
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers untuk security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers khusus untuk uploads folder
[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (jika perlu)
[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://b13factory-garmentadv.netlify.app"