backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

media_folder: 'public/uploads'
public_folder: '/uploads'

site_url: https://b13factory-garmentadv.netlify.app
display_url: https://b13factory-garmentadv.netlify.app
logo_url: '/logo.png'
locale: 'id'

collections:
  - name: 'settings'
    label: 'Settings'
    files:
      - name: 'site'
        label: 'Site Settings'
        file: 'public/content/settings/site.json'
        fields:
          - { label: 'Site Title', name: 'title', widget: 'string' }
          - { label: 'Site Description', name: 'description', widget: 'text' }
          - { label: 'Logo', name: 'logo', widget: 'image', required: false }
          - { label: 'Favicon', name: 'favicon', widget: 'image', required: false }

      - name: 'contact'
        label: 'Contact Settings'
        file: 'public/content/settings/contact.json'
        fields:
          - { label: 'Company Name', name: 'company_name', widget: 'string' }
          - { label: 'Address', name: 'address', widget: 'text' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'WhatsApp', name: 'whatsapp', widget: 'string' }
          - { label: 'Business Hours', name: 'business_hours', widget: 'text' }

  - name: 'home'
    label: 'Home Page'
    files:
      - name: 'hero'
        label: 'Hero Banner'
        file: 'public/content/home/hero.json'
        fields:
          - label: 'Slides'
            name: 'slides'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Background Image', name: 'image', widget: 'image' }
              - { label: 'Button Text', name: 'button_text', widget: 'string', required: false }
              - { label: 'Button Link', name: 'button_link', widget: 'string', required: false }

      - name: 'featured_products'
        label: 'Featured Products'
        file: 'public/content/home/featured-products.json'
        fields:
          - { label: 'Section Title', name: 'title', widget: 'string' }
          - label: 'Featured Product'
            name: 'featured'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Button Text', name: 'button_text', widget: 'string' }
              - { label: 'Button Link', name: 'button_link', widget: 'string' }
          - label: 'Product List'
            name: 'products'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }

      - name: 'services'
        label: 'Our Services'
        file: 'public/content/home/services.json'
        fields:
          - { label: 'Section Title', name: 'title', widget: 'string' }
          - { label: 'Section Description', name: 'description', widget: 'text' }
          - label: 'Services'
            name: 'services'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Icon Color', name: 'color', widget: 'select', options: ['blue', 'green', 'orange'] }
              - label: 'Features'
                name: 'features'
                widget: 'list'
                fields:
                  - { label: 'Feature', name: 'name', widget: 'string' }

  - name: 'products'
    label: 'Products'
    folder: 'public/content/products'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'select', options: ['kaos', 'bordir', 'advertising', 'merchandise'] }
      - { label: 'Price', name: 'price', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Short Description', name: 'excerpt', widget: 'text' }
      - { label: 'Full Description', name: 'body', widget: 'markdown' }
      - { label: 'Featured Product', name: 'featured', widget: 'boolean', default: false }

  - name: 'articles'
    label: 'Articles'
    folder: 'public/content/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'select', options: ['tips', 'teknik', 'news', 'tutorial'] }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Author', name: 'author', widget: 'string', default: 'Admin B13' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Article', name: 'featured', widget: 'boolean', default: false }

  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'public/content/portfolio'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Project Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'select', options: ['garment', 'bordir', 'advertising', 'merchandise'] }
      - { label: 'Client Name', name: 'client', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Project Description', name: 'description', widget: 'markdown' }
      - { label: 'Deliverables', name: 'deliverables', widget: 'list', fields: [{label: 'Item', name: 'item', widget: 'string'}] }
      - { label: 'Featured Project', name: 'featured', widget: 'boolean', default: false }