backend:
name: git-gateway
branch: main
commit_messages:
    create: "Create {{collection}} \"{{slug}}\""
    create: "Buat {{collection}} \"{{slug}}\""
update: "Update {{collection}} \"{{slug}}\""
    delete: "Delete {{collection}} \"{{slug}}\""
    delete: "Hapus {{collection}} \"{{slug}}\""
uploadMedia: "Upload \"{{path}}\""
    deleteMedia: "Delete \"{{path}}\""
    deleteMedia: "Hapus \"{{path}}\""

media_folder: "assets/uploads"
public_folder: "/assets/uploads"
publish_mode: editorial_workflow

collections:
- name: "pages"
    label: "Pages"
    label: "Halaman"
files:
- file: "content/home.json"
label: "Home Page"
name: "home"
fields:
- {label: "Judul Website", name: "title", widget: "string"}
- {label: "Deskripsi", name: "description", widget: "text"}
          - 
            label: "Hero Slider"
            name: "hero"
            widget: "list"
            fields:
              - {label: "Judul", name: "title", widget: "string"}
              - {label: "Subjudul", name: "subtitle", widget: "string"}
              - {label: "Gambar", name: "image", widget: "image"}
          - 
            label: "Info Rotator"
            name: "info"
            widget: "list"
            field: {label: "Info", name: "text", widget: "string"}
          - 
            label: "Layanan"
            name: "services"
            widget: "list"
            fields:
              - {label: "Icon", name: "icon", widget: "string"}
              - {label: "Judul", name: "title", widget: "string"}
              - {label: "Deskripsi", name: "description", widget: "text"}
          - 
            label: "Target Pasar"
            name: "market"
            widget: "list"
            fields:
              - {label: "Icon", name: "icon", widget: "string"}
              - {label: "Judul", name: "title", widget: "string"}
          - 
            label: "Spesifikasi"
            name: "specs"
            widget: "list"
            fields:
              - {label: "Judul", name: "title", widget: "string"}
              - {label: "Deskripsi", name: "description", widget: "text"}
          - 
            label: "Media Sosial"
            name: "social"
            widget: "list"
            fields:
              - {label: "Icon", name: "icon", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}

      - file: "content/about.json"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Judul", name: "title", widget: "string"}
          - {label: "Deskripsi", name: "description", widget: "markdown"}
          - {label: "Gambar", name: "image", widget: "image"}
          - {label: "Alamat", name: "address", widget: "string"}
          - {label: "Telepon", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}

- name: "products"
    label: "Products"
    label: "Produk"
folder: "content/product"
create: true
slug: "{{slug}}"
    summary: "{{title}} - {{category}}"
fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "Gambar", name: "image", widget: "image"}
- {label: "Badge", name: "badge", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Kategori", name: "category", widget: "string"}

- name: "articles"
    label: "Articles"
    label: "Artikel"
folder: "content/articles"
create: true
slug: "{{slug}}"
    summary: "{{title}} - {{category}}"
fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Penulis", name: "author", widget: "string"}
      - {label: "Kategori", name: "category", widget: "string"}
      - {label: "Gambar", name: "image", widget: "image"}
      - {label: "Kutipan", name: "excerpt", widget: "text"}
- {label: "URL", name: "url", widget: "string"}

- name: "downloads"
    label: "Downloads"
    label: "Download"
folder: "content/downloads"
create: true
slug: "{{slug}}"
    summary: "{{title}} - {{category}}"
fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}
- {label: "File", name: "file", widget: "file"}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string"}

  - name: "settings"
    label: "Settings"
    files:
      - file: "content/about.json"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
      - {label: "Ukuran", name: "size", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Kategori", name: "category", widget: "string"}
