backend:
  name: git-gateway
  branch: main   # kalau repo kamu masih pakai "master", ganti jadi master

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        format: "json"
        fields:
          - { label: "Judul Website", name: "title", widget: "string" }
          - { label: "Deskripsi Singkat", name: "description", widget: "text" }
