backend:
  name: git-gateway
  branch: main   # ganti ke "master" jika repo default branch masih master

media_folder: "assets/uploads"   # tempat simpan file di repo
public_folder: "/assets/uploads" # akses file dari website

collections:
  # ========== HOME ==========
  - name: "home"
    label: "Home"
    file: "content/home.json"
    format: "json"
    fields:
      - { label: "Judul Website", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "description", widget: "text" }
      - label: "Slider"
        name: "slider"
        widget: "list"
        fields:
          - { label: "Gambar", name: "image", widget: "image" }
          - { label: "Teks", name: "text", widget: "string" }
      - label: "Info Rotator"
        name: "info"
        widget: "list"
        field: { label: "Teks", name: "text", widget: "string" }
      - label: "Layanan"
        name: "services"
        widget: "list"
        fields:
          - { label: "Ikon", name: "icon", widget: "string" }
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Deskripsi", name: "description", widget: "text" }
      - label: "Pasar"
        name: "market"
        widget: "list"
        fields:
          - { label: "Ikon", name: "icon", widget: "string" }
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Deskripsi", name: "description", widget: "text" }
      - label: "Spesifikasi"
        name: "specs"
        widget: "list"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Deskripsi", name: "description", widget: "text" }
      - label: "Social Media"
        name: "social"
        widget: "list"
        fields:
          - { label: "Nama", name: "name", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Ikon", name: "icon", widget: "string" }

  # ========== ABOUT ==========
  - name: "about"
    label: "About"
    file: "content/about.json"
    format: "json"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "description", widget: "markdown" }
      - { label: "Foto", name: "image", widget: "image" }
      - { label: "Alamat", name: "address", widget: "string" }
      - { label: "Telepon", name: "phone", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }

  # ========== PRODUCTS ==========
  - name: "products"
    label: "Products"
    file: "content/products/index.json"
    format: "json"
    fields:
      - label: "Daftar Produk"
        name: "products"
        widget: "list"
        fields:
          - { label: "Nama Produk", name: "title", widget: "string" }
          - { label: "Deskripsi", name: "description", widget: "text" }
          - { label: "Gambar", name: "image", widget: "image" }
          - { label: "Badge", name: "badge", widget: "string", required: false }
          - { label: "Kategori", name: "category", widget: "string" }

  # ========== ARTICLES ==========
  - name: "articles"
    label: "Articles"
    file: "content/articles/index.json"
    format: "json"
    fields:
      - label: "Artikel"
        name: "articles"
        widget: "list"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Tanggal", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
          - { label: "Penulis", name: "author", widget: "string" }
          - { label: "Kategori", name: "category", widget: "string" }
          - { label: "Gambar", name: "image", widget: "image" }
          - { label: "Excerpt", name: "excerpt", widget: "text" }
          - { label: "URL", name: "url", widget: "string" }

  # ========== DOWNLOADS ==========
  - name: "downloads"
    label: "Downloads"
    file: "content/downloads/index.json"
    format: "json"
    fields:
      - label: "Daftar File"
        name: "downloads"
        widget: "list"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Deskripsi", name: "description", widget: "text" }
          - { label: "File", name: "file", widget: "file" }
          - { label: "Ukuran", name: "size", widget: "string" }
          - { label: "Tanggal", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
          - { label: "Kategori", name: "category", widget: "string" }
