backend:
  name: git-gateway
  branch: main   # sesuaikan branch repo kamu

publish_mode: editorial_workflow

media_folder: "static/img"    # tempat file di repo
public_folder: "/img"

site_url: https://b13factory-garmentadv.netlify.app

# Identity settings
identity:
  roles: ['admin']
