backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "home"
    label: "Home"
    file: "content/home.json"
    fields:
      - { label: "Judul Website", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "description", widget: "text" }
